workspace:
  base: /go
  path: src/golang.scot/project


pipeline:
  build:
    image: golang:${GO_VERSION}
    environment:
      - CGO_ENABLED=0
    commands:
      - go env
      - go get -u golang.org/x/vgo
      - vgo test ./...  && vgo build .

matrix:
  GO_VERSION:
    - 1.10.2
    - 1.10.3
