workspace:
  base: /go
  path: src/golang.scot/project


pipeline:
  build:
    image: golang:${GO_VERSION}
    commands:
      - go env
      - go get -u golang.org/x/vgo
      - vgo test ./...  && vgo build .

matrix:
  GO_VERSION:
    - 1.9.7
    - 1.10.3
