version: 2
dependencies:
  pre:
    - go get -u github.com/golang/dep/cmd/dep
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.8.3

    working_directory: /go/src/golang.scot/liberty

    steps:
      - checkout
      - run: dep ensure
      - run: go vet ./...
      - run: go test .
